[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "batching-lib"
version = "1.0.0"
description = "Python library for batching data"
readme = "README.md"
requires-python = ">=3.8"