name: Checks

on: [push]

jobs:
  test-lint-install:
    name: Test, Lint and Install
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip &&
             pip3 install -r requirements.dev.txt
        
      - name: Test
        run: python3 -m unittest discover -s ./tests -t ./tests

      - name: Lint
        run: flake8      
  
